version: '3'

# volumes:
#   nextcloud:
#   db:

services:
  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    # volumes:
    #   - db:/var/lib/mysql
    networks:
      - app-network
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}

  app:
    image: nextcloud
    ports:
      - 8082:80
    networks:
      - app-network
    volumes:
      - ./data:/var/www/html/data:cached
    restart: always

networks: 
  app-network:
    driver: bridge