version: '3'

# volumes:
#   nextcloud:
#   db:

services:
  db:
    image: mariadb
    container_name: mysql
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    # volumes:
    #   - db:/var/lib/mysql
    networks:
      - app-network
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}

  nextcloud:
    image: nextcloud
    container_name: nextcloud
    ports:
      - 8082:80
    networks:
      - app-network
    volumes:
      # - ./nextcloud:/var/www/html/data:cached
      - /media/external_1/nextcloud:/var/www/html/data:cached
    restart: always

  plex:
    image: linuxserver/plex
    container_name: plex
    ports:
      - 32400:32400
    # networks:
    #   - app-network
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      # - UMASK_SET=022 #optional
    volumes:
      # - ./system/plex/config:/config/Library/Application Support/Plex Media Server
      # - ./plex/mommy:/mommy
      - /media/external_1/Plex/Movies:/movies
      - /media/external_1/Plex/Daddy:/daddy
      - /media/external_1/Plex/Mommy:/mommy
      - /media/external_1/Plex/Shiloh:/shiloh
      # - /media/external_1/Plex/Story:/story
      - /media/external_1/Plex/music:/music
      # - /media/<externalpath>:/<path>
      # - /path for transcoding:/transcode
    restart: unless-stopped

  zoneminder:
    image: dlandon/zoneminder
    container_name: zoneminder
    network_mode: host
    ports:
      - 9001:9000
    environment:
      - SHMEM="50%"
      - PUID=99
      - PGID=100
      - INSTALL_HOOK=1
      - INSTALL_FACE=1
      - INSTALL_TINY_YOLO=1
      - INSTALL_YOLO=1
    volumes:
      - /media/external_1/Zoneminder:/config:rw
      - /media/external_1/Zoneminder/data:/var/cache/zoneminder:rw

networks: 
  app-network:
    driver: bridge